version: '2.2'
services:
   app1:
     image: ms-auth
     ports:
       - 4000:4000
     links:
       - mongo
     depends_on:
       - mongo
   app2:
     image: ms-user
     ports:
       - 4001:4001
     links:
       - mongo
     depends_on:
       - mongo
   mongo:
     image: mongo:latest
     ports:
       - 27018:27017
     volumes:
       - './dev/data/db:/data/db'